services:
  - type: web
    name: Id-Extractor-Bot  # <<< CHANGE IF YOURS IS DIFFERENT
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4